
CREATE TABLE `electric_inspect` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `table_code` VARCHAR(255) NOT NULL COMMENT '表码',
  `project_name` VARCHAR(255) NOT NULL COMMENT '项目名称',
  `cabinet_type` VARCHAR(255) NOT NULL COMMENT '柜型',
  `cabinet_num` VARCHAR(255) NOT NULL COMMENT '柜号',
  `inspector` VARCHAR(255) NOT NULL COMMENT '检验员',
  `date` VARCHAR(255) NOT NULL COMMENT '日期',
  `other` VARCHAR(255) COMMENT '其他',
  `remark` TEXT COMMENT '备注',
  `user_id` INT NOT NULL COMMENT '创建人',
  `equip_inspect_id` INT NOT NULL COMMENT '关联装备检验表',
  `loop_inspect_id` INT NOT NULL COMMENT '关联回路检验表',
  `inspect_item_id` INT NOT NULL COMMENT '关联检验项表',
  `other_no_regular_id` INT NOT NULL COMMENT '关联其他不合格项表',
  `gmt_created` DATETIME NOT NULL,
  `gmt_modified` DATETIME NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8  COMMENT '电器检验(单)表';


CREATE TABLE `equip_inspect` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `tester_num` VARCHAR(50) COMMENT '数字耐电压绝缘测试仪 编号',
  `power_on_num` VARCHAR(50) COMMENT '通电测试设备 编号',
  `pro_loop_num` VARCHAR(50) COMMENT '保护回路测量设备 编号',
  `drawer_confirm` INT DEFAULT -1 COMMENT '抽屉检确认',
  `process_confirm` INT DEFAULT -1 COMMENT '过程检验确认',
  `transfer_list_confirm` INT DEFAULT -1 COMMENT '流转单记录确认',
  `gmt_created` DATETIME NOT NULL,
  `gmt_modified` DATETIME NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8  COMMENT '装备检验表'; 


CREATE TABLE `loop_inspect` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `loop_vdc` VARCHAR(50) COMMENT '>1000Ω/V( )VDC',
  `voltage` VARCHAR(50) COMMENT 'Voltage( )V/min',
  `formula` VARCHAR(50) COMMENT '辅助回路公式',
  `l1_prevoltage` VARCHAR(50) COMMENT '耐压前(M Ω)',
  `l2_prevoltage` VARCHAR(50),
  `l3_prevoltage` VARCHAR(50),
  `n_prevoltage` VARCHAR(50),
  `assist_prevoltage` VARCHAR(50) COMMENT '辅助回路~~~',
  `l1_no_prevoltage` VARCHAR(50) COMMENT '耐压后(M Ω)',
  `l2_no_prevoltage` VARCHAR(50),
  `l3_no_prevoltage` VARCHAR(50),
  `n_no_prevoltage` VARCHAR(50),
  `assist_no_prevoltage` VARCHAR(50) COMMENT '辅助回路~~~',
  `l1_leakage_current` VARCHAR(50) COMMENT '泄露电流(mA)',
  `l2_leakage_current` VARCHAR(50),
  `l3_leakage_current` VARCHAR(50),
  `n_leakage_current` VARCHAR(50),
  `assist_leakage_current` VARCHAR(50) COMMENT '辅助回路~~~',
  `gmt_created` DATETIME NOT NULL,
  `gmt_modified` DATETIME NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '回路检验表'; 

CREATE TABLE `inspect_item` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `location_result` INT COMMENT '电源线取样位置(检查结果)——通电操作实验',
  `location_corrector` VARCHAR(30) COMMENT '整改人',
  `location_retest` VARCHAR(50) COMMENT '复检结果',
  
  `phase_sequence_result` INT COMMENT '检查一次回路相序',
  `phase_sequence_corrector` VARCHAR(30),
  `phase_sequence_retest` VARCHAR(50),
  `secondary_element_result` INT COMMENT '二次元件完整性',
  `secondary_element_corrector` VARCHAR(30),
  `secondary_element_retest` VARCHAR(50),
  `light_result` INT COMMENT '电器指示灯',
  `light_corrector` VARCHAR(30),
  `light_retest` VARCHAR(50),
  `meter_show_result` INT COMMENT '各类表计显示',
  `meter_show_corrector` VARCHAR(30),
  `meter_show_retest` VARCHAR(50),
  `meter_param_result` INT COMMENT '表计参数设置',
  `meter_param_corrector` VARCHAR(30),
  `meter_param_retest` VARCHAR(50),
  `signal_result` INT COMMENT '外引信号',
  `signal_corrector` VARCHAR(30),
  `signal_retest` VARCHAR(50),
  `electric_linkage_result` INT COMMENT '联调-电气连锁',
  `electric_linkage_corrector` VARCHAR(30),
  `electric_linkage_retest` VARCHAR(50),
  `cable_interlock_result` INT COMMENT '缆绳联锁',
  `cable_interlock_corrector` VARCHAR(30),
  `cable_interlock_retest` VARCHAR(50),
  `all_function_result` INT COMMENT '各功能测试',
  `all_function_corrector` VARCHAR(30),
  `all_function_retest` VARCHAR(50),
  `power_controller_result` INT COMMENT '功率因数控制器参数设置(检查结果)——CAP',
  `power_controller_corrector` VARCHAR(30),
  `power_controller_retest` VARCHAR(50),
  `switch_result` INT COMMENT '手动/自动投切',
  `switch_corrector` VARCHAR(30),
  `switch_retest` VARCHAR(50),
  `fan_temperature_result` INT COMMENT '风扇/温度传感器',
  `fan_temperature_corrector` VARCHAR(30),
  `fan_temperature_retest` VARCHAR(50),
  `arrester_result` INT COMMENT '避雷器',
  `arrester_corrector` VARCHAR(30),
  `arrester_retest` VARCHAR(50),
  `door_land_result` INT COMMENT '各门板接地点(检查结果)——接地连续性<0.1Ω',
  `door_land_corrector` VARCHAR(30),
  `door_land_retest` VARCHAR(50),
  `element_land_result` INT COMMENT '主要元件接地点',
  `element_land_corrector` VARCHAR(30),
  `element_land_retest` VARCHAR(50),
  `special_point_result` INT COMMENT '特殊注意点(检查结果)——开工单',
  `special_point_corrector` VARCHAR(30),
  `special_point_retest` VARCHAR(50),
  `blot_result` INT COMMENT '柜表污渍(检查结果)——清理',
  `blot_corrector` VARCHAR(30),
  `blot_retest` VARCHAR(50),
  `sundries_result` INT COMMENT '柜内杂物',
  `sundries_corrector` VARCHAR(30),
  `sundries_retest` VARCHAR(50),
  `gmt_created` DATETIME NOT NULL,
  `gmt_modified` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '检验项表';

CREATE TABLE `other_no_regular` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `one_text` text COMMENT '不合格项1',
  `two_text` text,
  `three_text` text,
  `four_text` text,
  `five_text` text,
  `six_text` text,
  `one_corrector` varchar(30) DEFAULT NULL COMMENT '整改人1',
  `two_corrector` varchar(30) DEFAULT NULL,
  `three_corrector` varchar(30) DEFAULT NULL,
  `four_corrector` varchar(30) DEFAULT NULL,
  `five_corrector` varchar(30) DEFAULT NULL,
  `six_corrector` varchar(30) DEFAULT NULL,
  `one_recheck` varchar(30) DEFAULT NULL COMMENT '复检1',
  `two_recheck` varchar(30) DEFAULT NULL,
  `three_recheck` varchar(30) DEFAULT NULL,
  `four_recheck` varchar(30) DEFAULT NULL,
  `five_recheck` varchar(30) DEFAULT NULL,
  `six_recheck` varchar(30) DEFAULT NULL,
  `gmt_created` datetime NOT NULL,
  `gmt_modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='其它不合格项表';
